# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='.proto',
  package='',
  serialized_pb='\n\x06.proto\"K\n\x06rfdata\x12\x0f\n\x07options\x18\x01 \x02(\t\x12\x0f\n\x07version\x18\x02 \x02(\t\x12\x11\n\tcmtconfig\x18\x03 \x02(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x02(\x02')




_RFDATA = descriptor.Descriptor(
  name='rfdata',
  full_name='rfdata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='options', full_name='rfdata.options', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='version', full_name='rfdata.version', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cmtconfig', full_name='rfdata.cmtconfig', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='rfdata.data', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=10,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['rfdata'] = _RFDATA

class rfdata(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RFDATA
  
  # @@protoc_insertion_point(class_scope:rfdata)

# @@protoc_insertion_point(module_scope)
