#!/bin/bash

. /afs/cern.ch/lhcb/software/releases/LBSCRIPTS/prod/InstallArea/scripts/LbLogin.sh &> /tmp/mytemp_log
rm /tmp/mytemp_log

. /afs/cern.ch/lhcb/software/releases/LBSCRIPTS/prod/InstallArea/scripts/SetupProject.sh LHCbDirac -q

export PYTHONPATH=$PYTHONPATH:/afs/cern.ch/lhcb/software/webapps/LHCbPR/Django-1.3.5:/afs/cern.ch/sw/lcg/external/pytools/1.8_python2.6/x86_64-slc5-gcc46-opt/lib/python2.6/site-packages

/afs/cern.ch/lhcb/software/webapps/LHCbPR/LHCbPR/django_apps/manage.py pushToDB

