#!/bin/sh

CMTCONFIG="x86_64-slc5-gcc43-opt"
HANDLERS="TimingHandler"
JOB_ID="1"
START=`date +"%Y-%m-%d,%T"`
END=`date +"%Y-%m-%d,%T"`

python26 collectRunResults.py -s ${START} -e ${END}   -p `hostname` -c ${CMTCONFIG} -j ${JOB_ID} -l ${HANDLERS}
