#!/bin/sh
#collect_script="/afs/cern.ch/user/e/ekiagias/workspace/LHCbPR/django_apps/collectRunResults.py"
export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.6/site-packages

start=`date +"%Y-%m-%d,%T"`
#gaudirun.py perf-test-1000.py
result="`pwd`/timing.xml"
end=`date +"%Y-%m-%d,%T"`
job_id="1"

cd ~/workspace/LHCbPR/django_apps

python26 collectRunResults.py -s ${start} -e ${end} -r ${result}  -p `hostname` -c $CMTCONFIG -j ${job_id}
#can be used ./runJob | python -mjson.tool > frafo.json to fix the output format
