#!/bin/bash

Django_folder="Django-1.3.7"
CURRENT_DIR=$( cd "$( dirname "${0}" )" && pwd )

. /afs/cern.ch/lhcb/software/releases/LBSCRIPTS/prod/InstallArea/scripts/LbLogin.sh

. SetupProject LCGCMT oracle pytools

if [ ! -d "${CURRENT_DIR}/${Django_foler}" ]; then
    echo "Django do not exist, gonna download it."
	${CURRENT_DIR}/getdjango
fi

export PYTHONPATH=${PYTHONPATH}:${CURRENT_DIR}/Django-1.3.7
